### PR TITLE
feat: Allow custom dispatcher. Add first draft of CRUD dispatcher.

### PR DESCRIPTION
**Pull request by iocanel**
This pull request adds a new feature which is the crud dispatcher. The crud dispatcher allows the mock webserver to act as a CRUD. So, instead of setting expectations for every single request, it works as an in memory crud, for storing, reading, updating and deleting resources.

It requires an object that will act as a mapper from paths to resources and vice versa and also an object that helps aggregating resources.

### CODE REVIEW

**Comment by iocanel** [comment]
@jstrachan: btw, how can we release nowdays?

**Comment by jstrachan** [comment]
@iocanel want me to cut a release? Just a case of a `Jenkinsfile` being added really

**Comment by iocanel** [comment]
@jstrachan: There is a Jenkinsfile already! But I no longer now where the release box lives.
So, please either cut the release or send me details on how to access the box nowdays.

**Comment by jstrachan** [comment]
@iocanel will do - any Jenkinsfile added will appear here: https://jenkins.cd.test.fabric8.io/ in the folder for the github organisation, repo & master branch. Though looks like that Jenkinsfile isn't a good one Java; lemme switch it with a better one and trigger a release...

**Comment by iocanel** [comment]
@jstrachan: Thanks!

**Comment by jstrachan** [comment]
syncing to maven central https://jenkins.cd.test.fabric8.io/job/fabric8io/job/mockwebserver/job/master/1/console

**Pull request merged**
